Traceback (most recent call last):
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def line(q):
    # Remember the surface tuple format is:
    # (coord_x, coord_y, normal_x, normal_y, jacobian)
    return q, 0 * q, 0 * q, np.ones_like(q), np.ones_like(q)
qbx_example(double_layer_matrix, surface_fnc=line, n=16, offset_mult=5, kappa=3, qbx_p=15)
------------------

[0;31m-----------------------------------------------------------------------[0m
[0;31mNameError[0m                             Traceback (most recent call last)
[0;32m<ipython-input-7-23411687e64e>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m     [0;31m# (coord_x, coord_y, normal_x, normal_y, jacobian)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0;32mreturn[0m [0mq[0m[0;34m,[0m [0;36m0[0m [0;34m*[0m [0mq[0m[0;34m,[0m [0;36m0[0m [0;34m*[0m [0mq[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mones_like[0m[0;34m([0m[0mq[0m[0;34m)[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mones_like[0m[0;34m([0m[0mq[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mqbx_example[0m[0;34m([0m[0mdouble_layer_matrix[0m[0;34m,[0m [0msurface_fnc[0m[0;34m=[0m[0mline[0m[0;34m,[0m [0mn[0m[0;34m=[0m[0;36m16[0m[0;34m,[0m [0moffset_mult[0m[0;34m=[0m[0;36m5[0m[0;34m,[0m [0mkappa[0m[0;34m=[0m[0;36m3[0m[0;34m,[0m [0mqbx_p[0m[0;34m=[0m[0;36m15[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-6-a7097b9d4fe1>[0m in [0;36mqbx_example[0;34m(kernel, surface_fnc, n, offset_mult, kappa, qbx_p)[0m
[1;32m     93[0m     [0mplt[0m[0;34m.[0m[0msubplot[0m[0;34m([0m[0;36m2[0m[0;34m,[0m [0;36m3[0m[0;34m,[0m [0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     94[0m     [0mplt[0m[0;34m.[0m[0mtitle[0m[0;34m([0m[0;34m'Naive error'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 95[0;31m     [0;32mwith[0m [0mwarnings[0m[0;34m.[0m[0mcatch_warnings[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     96[0m         [0mwarnings[0m[0;34m.[0m[0mfilterwarnings[0m[0;34m([0m[0;34m"ignore"[0m[0;34m,[0m [0mcategory[0m[0;34m=[0m[0mRuntimeWarning[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     97[0m     [0mlogerror[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlog10[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0mabs[0m[0;34m([0m[0mdisp_low[0m [0;34m-[0m [0mdisp_high[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'warnings' is not defined
NameError: name 'warnings' is not defined

